# Vocab
VOCAB:
  VOCAB_SIZE: 30000
  SPECIAL_TOKENS: ["<PAD>","<UNK>","<BOS>","<EOS>"]

DATA:
  TEST_SIZE: 0.15
  VAL_SIZE: 0.15

TRAINING:
  EPOCHS: 50
  LEARNING_RATE: 0.01
  BATCH_SIZE: 128
  MAX_LENGTH: 20

MODEL:
  EMBEDDING_DIM: 128
  HIDDEN_SIZE:  256
  NUM_LAYERS: 2
  DROPOUT: 0.3